### ISSUE TITLE
[Feature request] Parameter to specify format

### ISSUE THREAD

**Issue by apcamargo** [Maryam-Haghani/NEFFy#2]
Since extensions are not really standardized (e.g., FASTA alignments can have `.fasta`, `.afa`, `.fna`, or `.faa` extensions), it would be useful if we could specify the format of the input (and output) MSAs.

In my specific case, I need to process compressed MSAs. Since NEFFy doesn't support compressed files, I'm piping the data and reading from stdin:

```sh
gzip -dc msa.fna.gz | neff --file=/dev/stdin
```

 Since `/dev/stdin` doesn't have an extension, NEFFy doesn't know the input format. For the output, specifying the format could be useful for users that want to pass the result to stdout.

**Comment by Maryam-Haghani** [comment]
Thanks, @apcamargo, for your interest in using NEFFy and for bringing up this issue!

We’ve added an optional parameter, **`--format`**, which allows you to specify the MSA file format explicitly. If the format is not provided via the file extension, this parameter ensures that NEFFy can handle cases like reading a file from `stdin` without a proper file extension.
**Note:** If both a file extension and the --format parameter are provided, they must match to avoid conflicts.

This update is available in the [**format-issue2**](https://github.com/Maryam-Haghani/NEFFy/tree/format-issue2) branch. To test it out, clone the branch with:

```bash
git clone -b format-issue2 https://github.com/Maryam-Haghani/NEFFy
```

For your specific use case, after compiling the code, you can run:
```bash
gzip -dc msa.fna.gz | neff --file=/dev/stdin --format=fasta
```

Please give it a try and let us know if this update fulfills your requirements. While we’ve conducted initial tests, your feedback will help us ensure the feature works seamlessly. Once confirmed, we’ll merge the changes into the main branch.

Looking forward to your feedback!

**Comment by apcamargo** [comment]
Thanks for promptly working on this, @Maryam-Haghani!

Looks good to me. Maybe the parameter should be named `--input-format` in case you decide to add a `--output-format` in the future (to allow users to pass the output to `/dev/stdout`)?

**Comment by Maryam-Haghani** [comment]
I wanted to keep the naming aligned with --file, but I’ll keep your suggestion in mind for further improvements.
